version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '1234:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anlylistDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
